syntax = "proto3";

package authv1;

import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";

service AuthService {
  rpc Login(LoginRequest) returns (LoginResponse){}
  rpc Register (RegisterRequest) returns (RegisterResponse){}
  rpc NewTokens (NewTokensRequest) returns (NewTokensResponse) {}
  rpc VerifyAccount(VerifyAccountRequest) returns (VerifyAccountResponse) {}
}

message VerifyAccountRequest {
  int64 verify_code = 1 [
    (buf.validate.field).int64.gt = 0,
    json_name = "verify_code"
  ];
  reserved 2, 5;
}
message VerifyAccountResponse {
  string id = 1;
  string email = 2;
  string title = 3;
  string refresh_token = 4;
  string access_token = 5;
}
message NewTokensRequest {
  string refresh_token = 1;
}
message NewTokensResponse {
  string refresh_token = 1;
  string access_token = 2;
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string name = 3;
}
message RegisterResponse {
  string ok = 1;
}
message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string id = 1;
  string email = 2;
  string title = 3;
  string refresh_token = 4;
  string access_token = 5;
}