syntax = "proto3";

package authv1;

import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";

service AuthService {
  rpc Login(LoginRequest) returns (LoginResponse){}
  rpc Register (RegisterRequest) returns (RegisterResponse){}
  rpc NewTokens (NewTokensRequest) returns (NewTokensResponse) {}
  rpc VerifyAccount(VerifyAccountRequest) returns (VerifyAccountResponse) {}
  rpc ResendVerifyCode(ResendVerifyCodeRequest) returns (ResendVerifyCodeResponse){}
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse){}
  rpc ConfirmResetPassword(ConfirmResetPasswordRequest) returns (ConfirmResetPasswordResponse){}
}
message ConfirmResetPasswordRequest{
  string email = 1;
  string new_password = 2;
  int64 code = 3;
  reserved 4,6;
}
message ConfirmResetPasswordResponse{
  string email = 1;
  string new_password = 2;
  int64 code = 3;
  reserved 4,6;
}
message ResetPasswordRequest {
  string email = 1 [(buf.validate.field).string.email = true];
}
message ResetPasswordResponse{
  bool ok = 1;
}
message ResendVerifyCodeRequest {
  string email = 1;

  reserved 2, 5;
}
message ResendVerifyCodeResponse{
  bool ok = 1 ;
}
message VerifyAccountRequest {
  string email = 1;
  int64 verify_code = 2 [
    (buf.validate.field).int64.gt = 0,
    json_name = "verify_code"
  ];
  reserved 3, 5;
}
message VerifyAccountResponse {
  string id = 1 [(buf.validate.field).string.uuid = true];
  string email = 2;
  string title = 3;
  string refresh_token = 4;
  string access_token = 5;
}
message NewTokensRequest {
  string refresh_token = 1;
}
message NewTokensResponse {
  string refresh_token = 1;
  string access_token = 2;
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string name = 3;
}
message RegisterResponse {
  string ok = 1;
}
message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string id = 1;
  string email = 2;
  string title = 3;
  string refresh_token = 4;
  string access_token = 5;
}